defaultContentLanguage = "zh-tw"
baseURL = "https://fgzblog.com"
languageCode = "zh-tw"
title = "å‰›å“²çš„å€‹äººç¶²ç«™"
theme = "PaperMod"
enableInlineShortcodes = true
enableEmoji = true
enablerobotsTXT = true
hasCJKLanguage = true
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 10
defaultContentLanguageInSubdir = true

[permalinks]
posts = "/:year/:month/:slug/"
[minify] 
disableXML = true

 [[menu.main]]
 identifier = "search"
 name = "ğŸ” æœå°‹"
 url = "search"
 weight = 1

 [[menu.main]]
 identifier = "categories"
 name = "ğŸ—‚ï¸ åˆ†é¡"
 url = "categories"
 weight = 2

 [[menu.main]]
 identifier = "posts"
 name = "ğŸ“š æ–‡ç« "
 url = "posts"
 weight = 3

 [[menu.main]]
 identifier = "tags"
 name = "ğŸ”– æ¨™ç±¤"
 url = "tags"
 weight = 40

 [[menu.main]]
 identifier = "archives"
 name = "â± æ–‡ç« åº«"
 url = "archives"
 weight = 50

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
author = "FGZ"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideFooter = false
ShowWordCounts = true
VisitCount = true
ShowLastMod = true
ShowToc = true
TocOpen = true
comments = true
description = "èŒƒå‰›å“²çš„å€‹äººç¶²ç«™ï¼ŒèŒƒå‰›å“²ï¼Œè‡ªç”±è»Ÿé«”ï¼Œè®€æ›¸å¿ƒå¾—ï¼Œæ—…éŠï¼Œç¾é£Ÿï¼Œå°ä¸­ï¼Œè‹—æ —ï¼Œè·‘æ­¥ï¼Œå“²å­¸"
keywords = [ "Blog", "è·‘æ­¥", "PaperMod", "ç”Ÿæ´»é›œè¨˜", "è‡ªç”±è»Ÿé«”", "F-Droid" ]

 [params.cover]
 linkFullImages = true

 [params.homeInfoParams]
 enabled =true
 Title = "Hello,åœ¨é€™è£¡é‡è¦‹ä½ çœŸå¥½ï¼Œæ­¡è¿ä¾†åˆ°æˆ‘çš„ç¶²ç«™ã€‚"
 Content = """
 æ­¡è¿ä¾†åˆ°æˆ‘çš„å€‹äººç¶²ç«™ï¼Œé€™è£¡æœƒåˆ†äº«ä¸€äº›æˆ‘çš„æ—¥å¸¸é›œè¨˜ã€é–±è®€å¿ƒå¾—ã€å¥½ç”¨çš„è»Ÿç¡¬é«”åˆ†äº«ï¼Œä¸‹æ–¹é€£çµå¯ä»¥åˆ°æˆ‘çš„å€‹äººè‡‰æ›¸ã€YouTubeâ€¦ç­‰é€£çµï¼Œä¹Ÿæ­¡è¿ä½¿ç”¨RSSè¨‚é–±æœ¬ç«™ã€‚            
 """
 [[params.socialIcons]]
 name = "facebook"
 url = "https://www.facebook.com/gangzhef/"
 [[params.socialIcons]]
 name = "email"
 url = "mailto:j74127412@protonmail.com"
 [[params.socialIcons]]
 name = "strava"
 url = "https://www.strava.com/athletes/21667534"
 [[params.socialIcons]]
 name = "youtube"
 url = "https://www.youtube.com/user/fan728639/featured"
 [[params.socialIcons]]
 name = "RSS"
 url = "index.xml"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
style = "darcula"

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[assets]
 favicon = "/favicon.ico"
 favicon16x16 = "/favicon-16x16.png"
 favicon32x32 = "/favicon-32x32.png"
 apple_touch_icon = "/apple-touch-icon.png"
 safari_pinned_tab = "/safari-pinned-tab.svg"
