defaultContentLanguage: zh-tw
baseURL: https://fgzblog.com
languageCode: zh-tw
title: èŒƒå‰›å“²çš„éƒ¨è½æ ¼
theme: PaperMod
enableInlineShortcodes: true
enableEmoji: true
enablerobotsTXT: true
hasCJKLanguage: true
buildDrafts: false
buildFuture: false
buildExpired: false
defaultContentLanguageInSubdir: true
pagination:
  pagerSize: "6"
permalinks:
  posts: /:year/:month/:slug/
minify:
  disableXML: true
menu:
  main:
    - identifier: search
      name: ğŸ” æœå°‹
      url: search
      weight: 1
    - identifier: categories
      name: ğŸ—‚ï¸ åˆ†é¡
      url: categories
      weight: 2
    - identifier: posts
      name: ğŸ“š æ–‡ç« 
      url: posts
      weight: 3
    - identifier: tags
      name: ğŸ”– æ¨™ç±¤
      url: tags
      weight: 40
    - identifier: archives
      name: â± æ–‡ç« åº«
      url: archives
      weight: 50
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  env: production
  author: FGZ
  defaultTheme: auto
  disableThemeToggle: false
  DateFormat: 2006-01-02
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true
  ShowToc: true
  TocOpen: true
  comments: true
  description: èŒƒå‰›å“²çš„éƒ¨è½æ ¼ï¼ŒèŒƒå‰›å“²ï¼Œè‡ªç”±è»Ÿé«”ï¼Œè®€æ›¸å¿ƒå¾—ï¼Œæ—…éŠï¼Œç¾é£Ÿï¼Œå°ä¸­ï¼Œè‹—æ —ï¼Œè·‘æ­¥ï¼Œå“²å­¸
  keywords:
    - Blog
    - è·‘æ­¥
    - PaperMod
    - ç”Ÿæ´»é›œè¨˜
    - è‡ªç”±è»Ÿé«”
    - F-Droid
  ShowFullTextinRSS: true
  social: true
  cover:
    linkFullImages: true
  homeInfoParams:
    enabled: true
    Title: èŒƒå‰›å“²çš„éƒ¨è½æ ¼
    Content:
      " æ­¡è¿ä¾†åˆ°æˆ‘çš„å€‹äººç¶²ç«™ï¼Œé€™è£¡æœƒåˆ†äº«ä¸€äº›æˆ‘çš„æ—¥å¸¸é›œè¨˜ã€é–±è®€å¿ƒå¾—ã€å¥½ç”¨çš„è»Ÿç¡¬é«”åˆ†äº«ï¼Œæœ‰å¿ƒå¾—åˆ†äº«æ­¡è¿ä½¿ç”¨ Email èˆ‡æˆ‘è¯çµ¡ï¼Œä¹Ÿå»ºè­°ä½¿ç”¨ RSS
      è¨‚é–±æœ¬ç«™ã€‚           \

      \ "
  socialIcons:
    - name: email
      url: mailto:j74127412@protonmail.com
    - name: strava
      url: https://www.strava.com/athletes/21667534
    - name: youtube
      url: https://www.youtube.com/user/fan728639/featured
    - name: RSS
      url: index.xml
  busuanzi:
    enable: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: darcula
privacy:
  vimeo:
    disabled: false
    simple: true
  x:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
assets:
  favicon: /favicon.ico
  favicon16x16: /favicon-16x16.png
  favicon32x32: /favicon-32x32.png
  apple_touch_icon: /apple-touch-icon.png
  safari_pinned_tab: /safari-pinned-tab.svg
  disableHJLS: false
  ignoreErrors:
    - error-remote-getjson
