baseURL = "https://fgzblog.com"
buildDrafts = false
buildExpired = false
buildFuture = false
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true
enableEmoji = true
enableInlineShortcodes = true
enablerobotsTXT = true
hasCJKLanguage = true
languageCode = "zh-tw"
theme = "PaperMod"
title = "èŒƒå‰›å“²çš„éƒ¨è½æ ¼"

[assets]
apple_touch_icon = "/apple-touch-icon.png"
disableHJLS = false
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
ignoreErrors = ["error-remote-getjson"]
safari_pinned_tab = "/safari-pinned-tab.svg"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
style = "darcula"

[[menu.main]]
identifier = "search"
name = "ğŸ” æœå°‹"
url = "search"
weight = 1

[[menu.main]]
identifier = "categories"
name = "ğŸ—‚ï¸ åˆ†é¡"
url = "categories"
weight = 2

[[menu.main]]
identifier = "posts"
name = "ğŸ“š æ–‡ç« "
url = "posts"
weight = 3

[[menu.main]]
identifier = "tags"
name = "ğŸ”– æ¨™ç±¤"
url = "tags"
weight = 40

[[menu.main]]
identifier = "archives"
name = "â± æ–‡ç« åº«"
url = "archives"
weight = 50

[minify]
disableXML = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = "6"

[params]
DateFormat = "2006-01-02"
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowFullTextinRSS = true
ShowLastMod = true
ShowPostNavLinks = true
ShowReadingTime = true
ShowShareButtons = true
ShowToc = true
ShowWordCounts = true
TocOpen = true
VisitCount = true
author = "FGZ"
comments = true
defaultTheme = "auto"
description = "èŒƒå‰›å“²çš„éƒ¨è½æ ¼ï¼ŒèŒƒå‰›å“²ï¼Œè‡ªç”±è»Ÿé«”ï¼Œè®€æ›¸å¿ƒå¾—ï¼Œæ—…éŠï¼Œç¾é£Ÿï¼Œå°ä¸­ï¼Œè‹—æ —ï¼Œè·‘æ­¥ï¼Œå“²å­¸"
disableThemeToggle = false
displayFullLangName = true
env = "production"
hideFooter = false
keywords = ["Blog", "è·‘æ­¥", "PaperMod", "ç”Ÿæ´»é›œè¨˜", "è‡ªç”±è»Ÿé«”", "F-Droid"]
social = true

[params.busuanzi]
enable = true

[params.cover]
linkFullImages = true

[params.homeInfoParams]
Content = """
 æ­¡è¿ä¾†åˆ°æˆ‘çš„å€‹äººç¶²ç«™ï¼Œé€™è£¡æœƒåˆ†äº«ä¸€äº›æˆ‘çš„æ—¥å¸¸é›œè¨˜ã€é–±è®€å¿ƒå¾—ã€å¥½ç”¨çš„è»Ÿç¡¬é«”åˆ†äº«ï¼Œæœ‰å¿ƒå¾—åˆ†äº«æ­¡è¿ä½¿ç”¨ Email èˆ‡æˆ‘è¯çµ¡ï¼Œä¹Ÿå»ºè­°ä½¿ç”¨ RSS è¨‚é–±æœ¬ç«™ã€‚           
 """
Title = "èŒƒå‰›å“²çš„éƒ¨è½æ ¼"
enabled = true

[[params.socialIcons]]
name = "email"
url = "mailto:j74127412@protonmail.com"

[[params.socialIcons]]
name = "strava"
url = "https://www.strava.com/athletes/21667534"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/user/fan728639/featured"

[[params.socialIcons]]
name = "RSS"
url = "index.xml"

[permalinks]
posts = "/:year/:month/:slug/"

[privacy.instagram]
disabled = false
simple = true

[privacy.vimeo]
disabled = false
simple = true

[privacy.x]
disabled = false
enableDNT = true
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
